spring.application.name=online-shop

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

online-shop.app.secret=${JWT_SECRET}
online-shop.app.expirationMs=${JWT_EXPIRATION_MS:600000}
