spring.datasource.url=jdbc:postgresql://localhost:5432/your_db
spring.datasource.username=your_username
spring.datasource.password=your_password
online-shop.app.secret=your_very_long_secret_key_here
online-shop.app.expirationMs=600000
